### ISSUE TITLE
VectorSearchAlgorithmMetric cannot be imported!

### ISSUE THREAD

**Issue by bogazci** [Azure/azure-search-vector-samples#119]
I have tried both

**azure_search_documents-11.4.0b12-py3-none-any.whl** 

and

**azure_search_documents-11.4.0b11**

and in both i am not abel to reference to **VectorSearchAlgorithmMetric** where line

`from azure.search.documents.indexes.models import VectorSearchAlgorithmMetric`

throws error: 

`ImportError: cannot import name 'VectorSearchAlgorithmMetric' from 'azure.search.documents.indexes.models' (/usr/local/lib/python3.10/dist-packages/azure/search/documents/indexes/models/__init__.py)
`

**Comment by shivachittamuru** [comment]
I am getting the same error as well.

**Comment by farzad528** [comment]
Hi this should be fixed if you use the azure_search_documents-11.4.0b12-py3-none-any.whl, can you verify you are indeed using that version?

Alternatviely, you can remove the import and in your vector index configuration simply just pass the string value (E.g. metric="cosine")

**Comment by farzad528** [comment]
Hi this is resolved in the latest 11.5 version.

**Comment by XiyueSun** [comment]
> I have tried both
> 
> **azure_search_documents-11.4.0b12-py3-none-any.whl**
> 
> and
> 
> **azure_search_documents-11.4.0b11**
> 
> and in both i am not abel to reference to **VectorSearchAlgorithmMetric** where line
> 
> `from azure.search.documents.indexes.models import VectorSearchAlgorithmMetric`
> 
> throws error:
> 
> `ImportError: cannot import name 'VectorSearchAlgorithmMetric' from 'azure.search.documents.indexes.models' (/usr/local/lib/python3.10/dist-packages/azure/search/documents/indexes/models/__init__.py) `

hi, how do you find the azure_search_documents-11.4.0b12-py3-none-any.whl? Could you send the link plz?
