### ISSUE TITLE
Documentation and Python code sample mismatch

### ISSUE THREAD

**Issue by cagrimunyas** [Azure/azure-search-vector-samples#120]
[Microsoft Learn Docs for Vector Search ](https://learn.microsoft.com/en-us/azure/search/vector-search-how-to-query?tabs=python-vector-query%2Cfilter-2023-10-01-Preview#vector-query-request) > Python explicitly says:
`- Use the [Azure.Search.Documents 11.4.0b8] package for vector scenarios.` 
and then guide users to this repo while this repo ( [see sample for python](https://github.com/Azure/cognitive-search-vector-pr/blob/main/demo-python/code/azure-search-vector-python-sample.ipynb) ) uses 11.4.0b11.  

Please either update the docs or this repo to be consistent.

**Comment by farzad528** [comment]
@heidiSteen

**Comment by mattgotteiner** [comment]
Hi @cargimunyas,

The documentation has been updated to avoid mentioning a specific version, I am going to close this issue. Thanks for your report
