### ISSUE TITLE
AzureOpenAIEmbeddingSkill class has been removed  from Azure.Search.Documents" Version="11.5.0"

### ISSUE THREAD

**Issue by liborweigl** [Azure/azure-search-vector-samples#124]
Any idea what is replace for `AzureOpenAIEmbeddingSkill ` . It has been removed it from  Azure.Search.Documents  Version="11.5.0"
https://github.com/Azure/azure-search-vector-samples/blob/ca4809484908f571259afe48fedc099ee0bf710e/demo-dotnet/DotNetIntegratedVectorizationDemo/Program.cs#L86

I also when I was trying to run this demo with  Azure.Search.Documents  Version="11.5.0-beta.5" Skills created from demo  were timing out in Azure AI search.

Should I create endpoint for embedding and not use this `AzureOpenAIEmbeddingSkill `.  What should is the best precise for this scenario?

**Comment by farzad528** [comment]
Hi @liborweigl, please note that this is a class that's part of the integrated vectorization feature which is currently in preview so it will not be part of the latest stable version 11.5.0. 

You should use Azure.Search.Documents Version="11.5.0-beta.5" to use this feature. As for the timeout, you can set the timeout to be something greater than the default such as 30 minutes. See: https://learn.microsoft.com/dotnet/api/azure.search.documents.indexes.models.indexingparametersconfiguration.querytimeout?view=azure-dotnet-preview

Additionally, it's possible you are exceeding your AOAI rate limit. Perhaps you can try increasing the rate limit to the max amount on your AOAI deployed embedding model.

**Comment by liborweigl** [comment]
All make sense thank you @farzad528 .
