### ISSUE TITLE
How can I get azure-search-documents==11.4.0b12?

### ISSUE THREAD

**Issue by XiyueSun** [Azure/azure-search-vector-samples#134]
As mentioned in the ipynb, it is preview version, and I looked up on the pypi website there is not any code or etc?

**Comment by rafaspadilha** [comment]
It is available here: 
[https://github.com/Azure/azure-search-vector-samples/tree/main/demo-python/whl](https://github.com/Azure/azure-search-vector-samples/tree/main/demo-python/whl)
