### ISSUE TITLE
filtering nested json with CS

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Azure/azure-search-vector-samples#151]
Hi there 👋 

I was wondering if there is a way to filter nested jsons with CS. For example, let's assume we have the following document stored

```json
{ "metadata" : { "foo" : { "id": "baa" }  } }
```

is there a way to filter documents based on the id? Haven'f find anything in the examples

Thank you,

Fra

**Comment by FrancescoSaverioZuppichini** [comment]
friendly pinging @mattgotteiner

**Comment by mattgotteiner** [comment]
Yes, you would need to use Complex Types

https://learn.microsoft.com/en-us/azure/search/search-howto-complex-data-types?tabs=portal
