### ISSUE TITLE
Facing an issue in azure search index

### ISSUE THREAD

**Issue by Nalin879** [Azure/azure-search-vector-samples#181]
from azure.search.documents.indexes import SearchIndexClient
from azure.search.documents.indexes.models import (
    SearchField,
    SearchFieldDataType,
    VectorSearch,
    HnswAlgorithmConfiguration,
    HnswParameters,
    VectorSearchAlgorithmMetric,
    ExhaustiveKnnAlgorithmConfiguration,
    ExhaustiveKnnParameters,
    VectorSearchProfile,
    AzureOpenAIVectorizer,
    AzureOpenAIParameters,
    SemanticConfiguration,
    SemanticSearch,
    SemanticPrioritizedFields,
    SemanticField,
    SearchIndex
)
cannot import name 'AzureOpenAIVectorizer' from 'azure.search.documents.indexes.models' (C:\Users\subramaniann\AppData\Local\anaconda3\Lib\site-packages\azure\search\documents\indexes\models\__init__.py)
version using azure-search-documents==11.6.0b1

**Comment by mattgotteiner** [comment]
`AzureOpenAIVectorizer` is present in this package. Can you please check `C:\Users\subramaniann\AppData\Local\anaconda3\Lib\site-packages\azure\search\documents\_version.py` and confirm it is 11.6.0b1?

**Comment by Nalin879** [comment]
something like this VERSION = "1.0.0b2"

**Comment by mattgotteiner** [comment]
Then it's not 11.6.0b1. Please reinstall this sdk using `pip install --upgrade azure-search-documents==11.6.0b1`
