### ISSUE TITLE
Web Api response status: BadRequest

### ISSUE THREAD

**Issue by sanket98a** [Azure/azure-search-vector-samples#224]
Web Api response status: 'BadRequest', Web Api response details: '{
"error": {
"message": "Too many inputs. The max number of inputs is 1. We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions.",
"type": "invalid_request_error",
"param": null,
"code": null
}
}
'

Same error i am also facing. anyone's prompt attention highly appreciated

**Comment by mattgotteiner** [comment]
HI can you please open a support request for this issue?
