### ISSUE TITLE
demo-javascript Pure vector search results always 1

### ISSUE THREAD

**Issue by pietheinstrengholt** [Azure/azure-search-vector-samples#226]
I've carefully followed all the instructions outlined in the readme for demo-javascript. Everything appears to be functioning correctly, except for the pure vector search which continually returns all items. Each item has a score of 1. It also seems to be returning all items consistently. Do you have any suggestions on what could potentially be going wrong?

**Comment by mattgotteiner** [comment]
The demo-javascript needs updating, I will take a look at this in the near future

**Comment by mattgotteiner** [comment]
You need to use vectorSearchOptions

https://github.com/Azure/azure-search-vector-samples/blob/080445b497380cce48c917c7a40a25da59d73be1/demo-javascript/code/azure-search-vector-sample.js#L233-L242
