### ISSUE TITLE
503 Failed to execute query because not enough resources were available to cover 100% of the index

### ISSUE THREAD

**Issue by arelsharon** [Azure/azure-search-vector-samples#234]
Hello,
I'm getting the error message in the title, on some of my requests (but not all of them) and haven't been able to find resources on what it means or how to solve it.
Would Appreciate any info.

Attached is aggregated error I had gotten, including some simple rate limiting ones

![a4322b2a-2bcc-403e-b7c2-a6785ca40a8f](https://github.com/Azure/azure-search-vector-samples/assets/150013111/c76bb08a-ec74-4336-855f-bcd875f4b118)

**Comment by mattgotteiner** [comment]
You are being throttled. Please review this documentation
https://learn.microsoft.com/en-us/azure/search/search-performance-analysis#throttling-behaviors
