### ISSUE TITLE
Indexer fails: Could not execute skill because Web Api skill response is invalid.

### ISSUE THREAD

**Issue by GijsVoogd** [Azure/azure-search-vector-samples#248]
Everything runs fine. After creating the indexer and checking it it shows:

![image](https://github.com/Azure/azure-search-vector-samples/assets/39165902/31e23dac-bb26-4bb0-b5fe-1d4cb2cdece3)

The resource uri is valid and works in all the other previous steps. 

Any thoughts?

**Comment by mattgotteiner** [comment]
Please open a support request for this issue - this appears to be a service issue
