### ISSUE TITLE
ImportError: cannot import name 'AzureOpenAIVectorizerParameters' from 'azure.search.documents.indexes.models'

### ISSUE THREAD

**Issue by zzulueta** [Azure/azure-search-vector-samples#273]
In query-rewrite.ipynb (https://github.com/Azure/azure-search-vector-samples/blob/main/demo-python/code/advanced-workflow/query-rewrite/query-rewrite.ipynb), I got the following error:

{
	"name": "ImportError",
	"message": "cannot import name 'AzureOpenAIVectorizerParameters' from 'azure.search.documents.indexes.models' (/home/vscode/.local/lib/python3.11/site-packages/azure/search/documents/indexes/models/__init__.py)",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[4], line 2
      1 from azure.search.documents.indexes import SearchIndexClient
----> 2 from azure.search.documents.indexes.models import (
      3     SimpleField,
      4     SearchFieldDataType,
      5     SearchableField,
      6     SearchField,
      7     VectorSearch,
      8     HnswAlgorithmConfiguration,
      9     VectorSearchProfile,
     10     SemanticConfiguration,
     11     SemanticPrioritizedFields,
     12     SemanticField,
     13     SemanticSearch,
     14     SearchIndex,
     15     AzureOpenAIVectorizer,
     16     AzureOpenAIVectorizerParameters
     17 )
     20 # Create a search index
     21 index_client = SearchIndexClient(
     22     endpoint=endpoint, credential=credential)

ImportError: cannot import name 'AzureOpenAIVectorizerParameters' from 'azure.search.documents.indexes.models' (/home/vscode/.local/lib/python3.11/site-packages/azure/search/documents/indexes/models/__init__.py)"
}

The issue seems to be coming from this code area:
vectorizers=[
        AzureOpenAIVectorizer(
            vectorizer_name="myVectorizer",
            parameters=AzureOpenAIVectorizerParameters(
                resource_url=azure_openai_endpoint,
                deployment_name=azure_openai_embedding_deployment,
                api_key=azure_openai_key,
                model_name=azure_openai_embedding_deployment
            )
        )
    ]

In https://github.com/Azure/azure-search-vector-samples/blob/main/demo-python/code/basic-vector-workflow/azure-search-vector-python-sample.ipynb, the code is identical except this:

vectorizers=[
        AzureOpenAIVectorizer(
            name="myVectorizer",
            azure_open_ai_parameters=AzureOpenAIParameters(
                resource_uri=azure_openai_endpoint,
                deployment_id=azure_openai_embedding_deployment,
                model_name=embedding_model_name,
                api_key=azure_openai_key
            )
        )
    ]

So should it be AzureOpenAIVectorizerParameters or AzureOpenAIParameters?

**Comment by HeidiSteen** [comment]
@zzulueta, there's breaking changes on API naming, so you really want to watch what package version you're using.  This change log has a list of all the APIs that have been renamed.  Use the name that's right for your package version.  https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/CHANGELOG.md#1160b5-2024-09-19
