### ISSUE TITLE
LlamaParse api_key   Value error, The API key is required.

### ISSUE THREAD

**Issue by san-lee-ai** [Azure/azure-search-vector-samples#284]
I got an error from https://github.com/Azure/azure-search-vector-samples/blob/main/demo-python/code/e2e-demos/azure-ai-search-llamaindex-multimodal-rag-demo.ipynb

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[37], line 10
      7 DOWNLOAD_PATH = "data_images_state_of_ai_report_2024"
      8 os.makedirs(DOWNLOAD_PATH, exist_ok=True)
---> 10 parser = LlamaParse(
     11     result_type="markdown",
     12     use_vendor_multimodal_model=True,
     13     azure_openai_endpoint=f"{AZURE_OPENAI_ENDPOINT}openai/deployments/{AZURE_OPENAI_CHAT_COMPLETION_DEPLOYED_MODEL_NAME}/chat/completions?api-version=2024-08-01-preview",
     14     azure_openai_api_version="2024-08-01-preview",
     15     azure_openai_key=AZURE_OPENAI_API_KEY,
     16 )
     18 # Parse document and extract images
     19 md_json_objs = parser.get_json_result("data/llamaparse/State of AI Report 2024.pdf")

File ~/miniconda3/envs/amamd/lib/python3.11/site-packages/pydantic/main.py:212, in BaseModel.__init__(self, **data)
    210 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    211 __tracebackhide__ = True
--> 212 validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
    213 if self is not validated_self:
    214     warnings.warn(
    215         'A custom validator is returning a value other than `self`.\n'
    216         "Returning anything other than `self` from a top level model validator isn't supported when validating via `__init__`.\n"
    217         'See the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.',
    218         category=None,
    219     )

ValidationError: 1 validation error for LlamaParse
api_key
  Value error, The API key is required. [type=value_error, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/value_error

I provided azure_open_ai_key properly, but it keeps throwing out the error.

**Comment by logan-markewich** [comment]
You still need a llama-parse API key

**Comment by san-lee-ai** [comment]
Thank you Logan, the code should be updated:

# Azure Blob Configuration
BLOB_CONNECTION_STRING = os.getenv("BLOB_CONNECTION_STRING")
BLOB_STORAGE_ACCOUNT_KEY = os.getenv("BLOB_STORAGE_ACCOUNT_KEY")
BLOB_CONTAINER_NAME = "ignite-demo-images"
**LLAMA_COULD_API_KEY = os.getenv("LLAMA_COULD_API_KEY")**

# Set up download path and parser
DOWNLOAD_PATH = "mla2004"
os.makedirs(DOWNLOAD_PATH, exist_ok=True)

parser = LlamaParse(
    result_type="markdown",
    use_vendor_multimodal_model=True,
    azure_openai_endpoint=f"{AZURE_OPENAI_ENDPOINT}openai/deployments/{AZURE_OPENAI_CHAT_COMPLETION_DEPLOYED_MODEL_NAME}/chat/completions?api-version=2024-08-01-preview",
    azure_openai_api_version="2024-08-01-preview",
    azure_openai_key=AZURE_OPENAI_API_KEY,
    **api_key=LLAMA_COULD_API_KEY,**
)
