### ISSUE TITLE
Including a highlight parameter in a Simple Vector Search results in a minimumCoverage error

### ISSUE THREAD

**Issue by nohanaga** [Azure/azure-search-vector-samples#49]
When I add a highlight parameter to the Single Vector Search query described [here](https://github.com/Azure/cognitive-search-vector-pr/blob/main/docs/vector-search-quickstart.md#single-vector-search), the following error is returned. I understand that in principle the highlight function cannot be used in a Single Vector Search query, but I think it would be better to add it to the Docs restrictions or change the error message as it confuses users.

`
{
    "error": {
        "code": "",
        "message": "Failed to execute query because not enough resources were available to cover 100% of the index (58.3333333333333% was covered). You may be reaching the limits of your provisioned capacity. Adjust the number of replicas/partitions,  reduce the rate of requests, or specify a lower value for the minimumCoverage parameter. See http://aka.ms/azure-search-throttling for more information."
    }
}
`

**Comment by farzad528** [comment]
Hi @nohanga can you DM me your search service name?

**Comment by farzad528** [comment]
Hi @nohanaga, this is a bug and we are actively working on fixing this. Thank you for your feedback.

**Comment by nohanaga** [comment]
Hi @farzad528, Thank you very much for your response.

**Comment by arelsharon** [comment]
> Hi @nohanaga, this is a bug and we are actively working on fixing this. Thank you for your feedback.

Any update on this?

**Comment by farzad528** [comment]
Hi all this is resolved:
![image](https://github.com/Azure/azure-search-vector-samples/assets/40604067/89c2a1a1-91d3-49e2-8ec2-b5b141871ff6)
